version: '2.1'

services:
  code:
    image: code
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3007:3007
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js