version: '3'

services:

  summaryserver:
    build: ./
    ports:
      - '80:3007'
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - database
